title: Pokédex
description: pokedex
theme: just-the-docs

url: https://JorgeGP10.github.io

aux_links:
  1a Generación:
    - https://www.wikidex.net/wiki/Lista_de_Pok%C3%A9mon_de_la_primera_generaci%C3%B3n

  Template Repository: https://github.com/just-the-docs/just-the-docs-template
