title: Pokédex
description: pokedex
theme: just-the-docs

url: https://JorgeGP10.github.io

aux_links:
  Github:
    - https://github.com/JorgeGP10/JorgeGP10.github.io

  Template Repository: https://github.com/just-the-docs/just-the-docs-template
