title: Pokédex
description: pokedex
theme: just-the-docs
color_scheme: dark

url: https://JorgeGP10.github.io
favicon_ico: "https://i.etsystatic.com/11279093/r/il/d6ac58/1799315681/il_570xN.1799315681_ii1x.jpg"
nav_external_links:
  - title: 1a Generación
    url: https://www.wikidex.net/wiki/Lista_de_Pok%C3%A9mon_de_la_primera_generaci%C3%B3n
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

aux_links:
  Github:
    - https://github.com/JorgeGP10/JorgeGP10.github.io

  Template Repository: https://github.com/just-the-docs/just-the-docs-template
