title: Pokédex
description: pokedex
theme: just-the-docs
color_scheme: dark

url: https://JorgeGP10.github.io
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXWi8leBYq9kMNoVbXnesFi2ikfdsEI02Mw8M9FewDuwXX0sPqxvvX6QFoXrGBovC1qxo&usqp=CAU
nav_external_links:
  - title: 1a Generación
    url: https://www.wikidex.net/wiki/Lista_de_Pok%C3%A9mon_de_la_primera_generaci%C3%B3n
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

aux_links:
  Github:
    - https://github.com/JorgeGP10/JorgeGP10.github.io

  Template Repository: https://github.com/just-the-docs/just-the-docs-template
